$(eval $(call addlib,test))

TEST_SRCS-y += $(TEST_BASE)/test_pr_564.c
TEST_SRCS-y += $(TEST_BASE)/test_pr_565.c
TEST_SRCS-y += $(TEST_BASE)/main.c
TEST_SRCS-y += $(TEST_BASE)/helper.s
UK_PROVIDED_SYSCALLS-$(CONFIG_LIBVFSCORE) += fork-0
